package com.paulmerchants.gold.model.newmodel

data class PaymentDetailsDTO(
    val acquirer_data: String?,
    val amount: Double?,
    val amount_refunded: Int?,
    val bank: String?,
    val captured: Boolean?,
    val card: Any?,
    val card_id: String?,
    val contact: String?,
    val created_at: Long?,
    val currency: String?,
    val description: String?,
    val email: String?,
    val entity: String?,
    val error_code: String?,
    val error_description: String?,
    val error_reason: String?,
    val error_source: String?,
    val error_step: String?,
    val fee: Int?,
    val id: String?,
    val international: Boolean?,
    val invoice_id: String?,
    val method: String?,
    val notes: String?,
    val order_id: String?,
    val refund_status: String?,
    val status: String?,
    val tax: Int?,
    val upi: Any?,
    val vpa: String?,
    val wallet: String?
)