package com.paulmerchants.gold.enums

enum class ServiceType(val type: Int) {
    SERVICES(0),
    TRANSACTION(1),
    SETTINGS(2),
    REWARDS(3),
    ACTION_VIEW_TRANSACTION(4),
    ACTION_VIEW_UPI_SETTINGS(5),
    ACTION_VIEW_CARD_SETTINGS(6),
    ACTION_VIEW_ACC_SETTINGS(7),
    ACTION_VIEW_ADD_OR_MNG_ADD(8),
    ACTION_WHAT_R_WE(9),
    ACTION_PRIVACY_POLICY(10),
    ACTION_BLV_IN_SECURITY(11),
    ACTION_T_N_C(12),
    ACTION_FAQ(13),
    ACTION_LOAN_OVERVIEW(14),
    ACTION_LOANS_RENEWAL(15),
    ACTION_BILLS_RECHARGES(16),
    ACTION_OTHER_BILLS(17),
    ACTION_GOLD_LOAN(18),
    ACTION_OTHER_EMIS_PAYMENT(19),
    ACTION_TRANSACTIONS(20),
    ACTION_PREPAID_CARD_RECHARGES(21),
    ACTION_CRED_SCORE(22)
}